import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import javax.swing.JOptionPane;


/**
 *
 * @author RAMIRO
 */
public class Loterias extends javax.swing.JFrame {
    Locale l = new Locale ("pt" , "BR");
    NumberFormat nf = NumberFormat.getCurrencyInstance(l);
    StringBuilder sb, sb1, sb2;
    int qtdDezenasMega;
    int qtdDezenasQuina;
    int qtdDezenasLotomania;
    int qtdDezenasLotofacil;
    int qtdDezenasDuplasena;
    
    /**
     * Creates new form Loterias
     */
    public Loterias() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cbMegasena = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        tfMegasena = new javax.swing.JTextField();
        btMegasena = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        taMegasena = new javax.swing.JTextArea();
        btLimparMega = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        cbDuplasena = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        tfDuplasena = new javax.swing.JTextField();
        btDuplasena = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        taDuplasena = new javax.swing.JTextArea();
        btLmparDuplasena = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        cbQuina = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        tfQuina = new javax.swing.JTextField();
        btQuina = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        taQuina = new javax.swing.JTextArea();
        btLimparQuina = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        cbLotofacil = new javax.swing.JComboBox<>();
        jLabel24 = new javax.swing.JLabel();
        tfLotofacil = new javax.swing.JTextField();
        btLotofacil = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        taLotofacil = new javax.swing.JTextArea();
        btLimparLotofacil = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btLotomania = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        taLotomania = new javax.swing.JTextArea();
        btLimparLotomania = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Loterias by rolipam INFORMÁTICA");
        setLocation(new java.awt.Point(400, 150));
        setMaximumSize(new java.awt.Dimension(500, 500));
        setMinimumSize(new java.awt.Dimension(500, 500));
        setResizable(false);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/MEGA-SENA.jpg"))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Sorteia de 6 a 15 dezenas entre 01 e 60. Valor da aposta a partir de R$ 3,50. Ganha acertando 6, 5 ou 4");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("números. Os sorteios são realizados quartas e sábados.");

        jLabel11.setText("Escolha quantas dezenas quer jogar:");

        cbMegasena.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escolha", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15" }));
        cbMegasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMegasenaActionPerformed(evt);
            }
        });

        jLabel12.setText("Valor do Jogo:");

        tfMegasena.setEditable(false);
        tfMegasena.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tfMegasena.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfMegasena.setFocusable(false);

        btMegasena.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        btMegasena.setText("SORTEAR");
        btMegasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMegasenaActionPerformed(evt);
            }
        });

        taMegasena.setColumns(20);
        taMegasena.setFont(new java.awt.Font("Verdana", 0, 26)); // NOI18N
        taMegasena.setLineWrap(true);
        taMegasena.setRows(5);
        jScrollPane2.setViewportView(taMegasena);

        btLimparMega.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        btLimparMega.setText("LIMPAR");
        btLimparMega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparMegaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 584, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbMegasena, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfMegasena, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btMegasena)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btLimparMega)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cbMegasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(tfMegasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btMegasena)
                    .addComponent(btLimparMega))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Mega-Sena", jPanel1);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/DUPLA-SENA.jpg"))); // NOI18N

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("Sorteia de 6 a 15 dezenas entre 01 e 50. Valor da aposta a partir de R$ 2,00. Ganha acertando 6, 5, 4 ou");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("3 números. Os sorteios são realizados terças, quintas e sábados.");

        jLabel15.setText("Escolha quantas dezenas quer jogar:");

        cbDuplasena.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escolha", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15" }));
        cbDuplasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDuplasenaActionPerformed(evt);
            }
        });

        jLabel16.setText("Valor do Jogo:");

        tfDuplasena.setEditable(false);
        tfDuplasena.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tfDuplasena.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfDuplasena.setFocusable(false);

        btDuplasena.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        btDuplasena.setText("SORTEAR");
        btDuplasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDuplasenaActionPerformed(evt);
            }
        });

        taDuplasena.setColumns(20);
        taDuplasena.setFont(new java.awt.Font("Verdana", 0, 26)); // NOI18N
        taDuplasena.setLineWrap(true);
        taDuplasena.setRows(5);
        jScrollPane3.setViewportView(taDuplasena);

        btLmparDuplasena.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        btLmparDuplasena.setText("LIMPAR");
        btLmparDuplasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLmparDuplasenaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 584, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbDuplasena, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfDuplasena, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btDuplasena)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btLmparDuplasena)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(cbDuplasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(tfDuplasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btDuplasena)
                    .addComponent(btLmparDuplasena))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Dupla-Sena", jPanel2);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/QUINA.jpg"))); // NOI18N

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setText("Sorteia de 5 a 15 dezenas entre 01 e 80. Valor da aposta a partir de R$ 1,50. Ganha acertando 5, 4, 3 ou");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setText("2 números. Os sorteios são realizados diariamente de segunda a sábado.");

        jLabel19.setText("Escolha quantas dezenas quer jogar:");

        cbQuina.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escolha", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15" }));
        cbQuina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbQuinaActionPerformed(evt);
            }
        });

        jLabel20.setText("Valor do Jogo:");

        tfQuina.setEditable(false);
        tfQuina.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tfQuina.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfQuina.setFocusable(false);

        btQuina.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        btQuina.setText("SORTEAR");
        btQuina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btQuinaActionPerformed(evt);
            }
        });

        taQuina.setColumns(20);
        taQuina.setFont(new java.awt.Font("Verdana", 0, 26)); // NOI18N
        taQuina.setLineWrap(true);
        taQuina.setRows(5);
        jScrollPane4.setViewportView(taQuina);

        btLimparQuina.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        btLimparQuina.setText("LIMPAR");
        btLimparQuina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparQuinaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 584, Short.MAX_VALUE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbQuina, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfQuina, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btQuina)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btLimparQuina)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane4))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(cbQuina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(tfQuina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btQuina)
                    .addComponent(btLimparQuina))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Quina", jPanel3);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/logo_lotofacil.png"))); // NOI18N

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel21.setText("Sorteia 15 a 18 dezenas entre 01 e 25. Valor da aposta a partir de R$ 2,00. Ganha acertando 15, 14, 13, ");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel22.setText("12 ou 11 números. Os sorteios são realizados segundas, quartas e sextas.");

        jLabel23.setText("Escolha quantas dezenas quer jogar:");

        cbLotofacil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escolha", "15", "16", "17", "18" }));
        cbLotofacil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbLotofacilActionPerformed(evt);
            }
        });

        jLabel24.setText("Valor do Jogo:");

        tfLotofacil.setEditable(false);
        tfLotofacil.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tfLotofacil.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfLotofacil.setFocusable(false);

        btLotofacil.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        btLotofacil.setText("SORTEAR");
        btLotofacil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLotofacilActionPerformed(evt);
            }
        });

        taLotofacil.setColumns(20);
        taLotofacil.setFont(new java.awt.Font("Verdana", 0, 26)); // NOI18N
        taLotofacil.setLineWrap(true);
        taLotofacil.setRows(5);
        jScrollPane5.setViewportView(taLotofacil);

        btLimparLotofacil.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        btLimparLotofacil.setText("LIMPAR");
        btLimparLotofacil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparLotofacilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, 584, Short.MAX_VALUE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbLotofacil, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfLotofacil, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btLotofacil)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btLimparLotofacil)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane5))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(cbLotofacil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24)
                    .addComponent(tfLotofacil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btLotofacil)
                    .addComponent(btLimparLotofacil))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Lotofácil", jPanel4);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/logo_lotomania.png"))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Sorteia 50 dezenas entre 00 e 99. Valor da aposta único de R$ 1,50. Ganha acertando 20, 19, 18, 17, 16, ");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("15 ou nenhum número. Os sorteios são realizados terças e sextas.");

        btLotomania.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        btLotomania.setText("SORTEAR");
        btLotomania.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLotomaniaActionPerformed(evt);
            }
        });

        taLotomania.setEditable(false);
        taLotomania.setColumns(20);
        taLotomania.setFont(new java.awt.Font("Verdana", 0, 26)); // NOI18N
        taLotomania.setLineWrap(true);
        taLotomania.setRows(5);
        taLotomania.setFocusable(false);
        jScrollPane1.setViewportView(taLotomania);

        btLimparLotomania.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        btLimparLotomania.setText("LIMPAR");
        btLimparLotomania.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparLotomaniaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 584, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                        .addComponent(btLotomania)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btLimparLotomania)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btLotomania)
                    .addComponent(btLimparLotomania))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Lotomania", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbMegasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMegasenaActionPerformed
        
        double valorApostaMega;
        
        if(cbMegasena.getSelectedItem().equals("6")){
            qtdDezenasMega = 6;
            valorApostaMega = 3.5;
            tfMegasena.setText(nf.format(valorApostaMega));
        }else if(cbMegasena.getSelectedItem().equals("7")){
            qtdDezenasMega = 7;
            valorApostaMega = 24.5;
            tfMegasena.setText(nf.format(valorApostaMega));
        }else if (cbMegasena.getSelectedItem().equals("8")){
            qtdDezenasMega = 8;
            valorApostaMega = 98.0;
            tfMegasena.setText(nf.format(valorApostaMega));
        }else if (cbMegasena.getSelectedItem().equals("9")){
            qtdDezenasMega = 9;
            valorApostaMega = 294.0;
            tfMegasena.setText(nf.format(valorApostaMega));
        }else if (cbMegasena.getSelectedItem().equals("10")){
            qtdDezenasMega = 10;
            valorApostaMega = 735.0;
            tfMegasena.setText(nf.format(valorApostaMega));
        }else if (cbMegasena.getSelectedItem().equals("11")){
            qtdDezenasMega = 11;
            valorApostaMega = 1617.0;
            tfMegasena.setText(nf.format(valorApostaMega));
        }else if (cbMegasena.getSelectedItem().equals("12")){
            qtdDezenasMega = 12;
            valorApostaMega = 3234.0;
            tfMegasena.setText(nf.format(valorApostaMega));
        }else if (cbMegasena.getSelectedItem().equals("13")){
            qtdDezenasMega = 13;
            valorApostaMega = 6006.0;
            tfMegasena.setText(nf.format(valorApostaMega));
        }else if (cbMegasena.getSelectedItem().equals("14")){
            qtdDezenasMega = 14;
            valorApostaMega = 10510.5;
            tfMegasena.setText(nf.format(valorApostaMega));
        }else if (cbMegasena.getSelectedItem().equals("15")){
            qtdDezenasMega = 15;
            valorApostaMega = 17517.5;
            tfMegasena.setText(nf.format(valorApostaMega));
        } else if (cbMegasena.getSelectedItem().equals("Escolha")){
            qtdDezenasMega = 0;
            valorApostaMega = 0.0;
            tfMegasena.setText("");
        }
        
    }//GEN-LAST:event_cbMegasenaActionPerformed

    private void btLimparMegaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparMegaActionPerformed
        cbMegasena.setSelectedItem("Escolha");
        tfMegasena.setText("");
        taMegasena.setText("");
    }//GEN-LAST:event_btLimparMegaActionPerformed

    private void btLmparDuplasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLmparDuplasenaActionPerformed
        cbDuplasena.setSelectedItem("Escolha");
        tfDuplasena.setText("");
        taDuplasena.setText("");
    }//GEN-LAST:event_btLmparDuplasenaActionPerformed

    private void btLimparQuinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparQuinaActionPerformed
        cbQuina.setSelectedItem("Escolha");
        tfQuina.setText("");
        taQuina.setText("");
    }//GEN-LAST:event_btLimparQuinaActionPerformed

    private void btLimparLotofacilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparLotofacilActionPerformed
        cbLotofacil.setSelectedItem("Escolha");
        tfLotofacil.setText("");
        taLotofacil.setText("");
    }//GEN-LAST:event_btLimparLotofacilActionPerformed

    private void btLimparLotomaniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparLotomaniaActionPerformed
        taLotomania.setText("");
    }//GEN-LAST:event_btLimparLotomaniaActionPerformed

    private void btMegasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMegasenaActionPerformed
        if(qtdDezenasMega == 0){
            JOptionPane.showMessageDialog(null, "Selecione a Quantidade de Dezenas que Deseja Jogar.");
        }else{
            String dezena;
            sb = new StringBuilder();
            List<String> megaSena = new ArrayList<>();
            for(int i = 0; i < qtdDezenasMega ; i++){
                dezena = GerarDezenas(1, 61);
                while(megaSena.contains(dezena)){
                    dezena = GerarDezenas(1, 61);
                }
                megaSena.add(dezena);
                
                sb.append("< ");
                sb.append(megaSena.get(i));
                sb.append(" >");   
            }
            String sorteioMega = sb.toString();
            taMegasena.setText(sorteioMega);
        }
    }//GEN-LAST:event_btMegasenaActionPerformed

    private void cbDuplasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDuplasenaActionPerformed
        double valorApostaDupla;
        
        if(cbDuplasena.getSelectedItem().equals("6")){
            qtdDezenasDuplasena = 6;
            valorApostaDupla = 2.0;
            tfDuplasena.setText(nf.format(valorApostaDupla));
        }else if(cbDuplasena.getSelectedItem().equals("7")){
            qtdDezenasDuplasena = 7;
            valorApostaDupla = 14.0;
            tfDuplasena.setText(nf.format(valorApostaDupla));
        }else if(cbDuplasena.getSelectedItem().equals("8")){
            qtdDezenasDuplasena = 8;
            valorApostaDupla = 56.0;
            tfDuplasena.setText(nf.format(valorApostaDupla));
        }else if(cbDuplasena.getSelectedItem().equals("9")){
            qtdDezenasDuplasena = 9;
            valorApostaDupla = 168.0;
            tfDuplasena.setText(nf.format(valorApostaDupla));
        }else if(cbDuplasena.getSelectedItem().equals("10")){
            qtdDezenasDuplasena = 10;
            valorApostaDupla = 420.0;
            tfDuplasena.setText(nf.format(valorApostaDupla));
        }else if(cbDuplasena.getSelectedItem().equals("11")){
            qtdDezenasDuplasena = 11;
            valorApostaDupla = 924.0;
            tfDuplasena.setText(nf.format(valorApostaDupla));
        }else if(cbDuplasena.getSelectedItem().equals("12")){
            qtdDezenasDuplasena = 12;
            valorApostaDupla = 1848.0;
            tfDuplasena.setText(nf.format(valorApostaDupla));
        }else if(cbDuplasena.getSelectedItem().equals("13")){
            qtdDezenasDuplasena = 13;
            valorApostaDupla = 3432.0;
            tfDuplasena.setText(nf.format(valorApostaDupla));
        }else if(cbDuplasena.getSelectedItem().equals("14")){
            qtdDezenasDuplasena = 14;
            valorApostaDupla = 6006.0;
            tfDuplasena.setText(nf.format(valorApostaDupla));
        }else if(cbDuplasena.getSelectedItem().equals("15")){
            qtdDezenasDuplasena = 15;
            valorApostaDupla = 10010.0;
            tfDuplasena.setText(nf.format(valorApostaDupla));
        }else if(cbDuplasena.getSelectedItem().equals("Escolha")){
            qtdDezenasDuplasena = 0;
            valorApostaDupla = 0.0;
            tfDuplasena.setText("");
        }
    }//GEN-LAST:event_cbDuplasenaActionPerformed

    private void btDuplasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDuplasenaActionPerformed
        if(qtdDezenasDuplasena == 0){
            JOptionPane.showMessageDialog(null, "Selecione a Quantidade de Dezenas que Deseja Jogar.");
        }else{
            String dezena;
            sb1 = new StringBuilder();
            List<String> duplaSena1 = new ArrayList<>();
            for(int i = 0; i < qtdDezenasDuplasena ; i++){
                dezena = GerarDezenas(1, 51);
                while(duplaSena1.contains(dezena)){
                    dezena = GerarDezenas(1, 51);
                }
                duplaSena1.add(dezena);
                
                sb1.append("< ");
                sb1.append(duplaSena1.get(i));
                sb1.append(" >");
            }
            sb2 = new StringBuilder();
            List<String> duplaSena2 = new ArrayList<>();
            for(int i = 0; i < qtdDezenasDuplasena ; i++){
                dezena = GerarDezenas(1, 51);
                while(duplaSena2.contains(dezena)){
                    dezena = GerarDezenas(1, 51);
                }
                duplaSena2.add(dezena);
                
                sb2.append("< ");
                sb2.append(duplaSena2.get(i));
                sb2.append(" >");
            }
            
            String Sorteio1duplasena = sb1.toString();
            String Sorteio2duplasena = sb2.toString();
            taDuplasena.setText("Sorteio 1: " + "\n" +Sorteio1duplasena + "\n\n" + "Sorteio 2: " + "\n" + Sorteio2duplasena);
        }        
    }//GEN-LAST:event_btDuplasenaActionPerformed

    private void cbQuinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbQuinaActionPerformed
        double valorApostaQuina;
        
        if(cbQuina.getSelectedItem().equals("5")){
            qtdDezenasQuina = 5;
            valorApostaQuina = 1.5;
            tfQuina.setText(nf.format(valorApostaQuina));
        }else if(cbQuina.getSelectedItem().equals("6")){
            qtdDezenasQuina = 6;
            valorApostaQuina = 9.0;
            tfQuina.setText(nf.format(valorApostaQuina));
        }else if(cbQuina.getSelectedItem().equals("7")){
            qtdDezenasQuina = 7;
            valorApostaQuina = 31.5;
            tfQuina.setText(nf.format(valorApostaQuina));
        }else if(cbQuina.getSelectedItem().equals("8")){
            qtdDezenasQuina = 8;
            valorApostaQuina = 84.0;
            tfQuina.setText(nf.format(valorApostaQuina));
        }else if(cbQuina.getSelectedItem().equals("9")){
            qtdDezenasQuina = 9;
            valorApostaQuina = 189.0;
            tfQuina.setText(nf.format(valorApostaQuina));
        }else if(cbQuina.getSelectedItem().equals("10")){
            qtdDezenasQuina = 10;
            valorApostaQuina = 378.0;
            tfQuina.setText(nf.format(valorApostaQuina));
        }else if(cbQuina.getSelectedItem().equals("11")){
            qtdDezenasQuina = 11;
            valorApostaQuina = 693.0;
            tfQuina.setText(nf.format(valorApostaQuina));
        }else if(cbQuina.getSelectedItem().equals("12")){
            qtdDezenasQuina = 12;
            valorApostaQuina = 1188.0;
            tfQuina.setText(nf.format(valorApostaQuina));
        }else if(cbQuina.getSelectedItem().equals("13")){
            qtdDezenasQuina = 13;
            valorApostaQuina = 1930.5;
            tfQuina.setText(nf.format(valorApostaQuina));
        }else if(cbQuina.getSelectedItem().equals("14")){
            qtdDezenasQuina = 14;
            valorApostaQuina = 3003.5;
            tfQuina.setText(nf.format(valorApostaQuina));
        }else if(cbQuina.getSelectedItem().equals("15")){
            qtdDezenasQuina = 15;
            valorApostaQuina = 4504.5;
            tfQuina.setText(nf.format(valorApostaQuina));
        }else if(cbQuina.getSelectedItem().equals("Escolha")){
            qtdDezenasQuina = 0;
            valorApostaQuina = 0.0;
            tfQuina.setText("");
        }
    }//GEN-LAST:event_cbQuinaActionPerformed

    private void btQuinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btQuinaActionPerformed
        if(qtdDezenasQuina == 0){
            JOptionPane.showMessageDialog(null, "Selecione a Quantidade de Dezenas que Deseja Jogar.");
        }else{
            String dezena;
            sb = new StringBuilder();
            List<String> quina = new ArrayList<>();
            for(int i = 0; i < qtdDezenasQuina ; i++){
                dezena = GerarDezenas(1, 81);
                while(quina.contains(dezena)){
                    dezena = GerarDezenas(1, 81);
                }
                quina.add(dezena);

                sb.append("< ");
                sb.append(quina.get(i));
                sb.append(" >");
            }
            String SorteioQuina = sb.toString();
            taQuina.setText(SorteioQuina);
        }
    }//GEN-LAST:event_btQuinaActionPerformed

    private void btLotomaniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLotomaniaActionPerformed
        qtdDezenasLotomania = 50;
        String dezena;
        sb = new StringBuilder();
        List<String> lotomania = new ArrayList<>();
            for(int i = 0; i < qtdDezenasLotomania ; i++){
                dezena = GerarDezenas(0, 100);
                while(lotomania.contains(dezena)){
                    dezena = GerarDezenas(0, 100);
                }
                lotomania.add(dezena);
                
                sb.append("< ");
                sb.append(lotomania.get(i));
                sb.append(" >");
            }
            String SorteioLotomania = sb.toString();
            taLotomania.setText(SorteioLotomania);
        
    }//GEN-LAST:event_btLotomaniaActionPerformed

    private void cbLotofacilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbLotofacilActionPerformed
        double valorApostaLotofacil;
        
        if(cbLotofacil.getSelectedItem().equals("15")){
            qtdDezenasLotofacil = 15;
            valorApostaLotofacil = 2.0;
            tfLotofacil.setText(nf.format(valorApostaLotofacil));
        }else if(cbLotofacil.getSelectedItem().equals("16")){
            qtdDezenasLotofacil = 16;
            valorApostaLotofacil = 32.0;
            tfLotofacil.setText(nf.format(valorApostaLotofacil));
        }else if(cbLotofacil.getSelectedItem().equals("17")){
            qtdDezenasLotofacil = 17;
            valorApostaLotofacil = 272.0;
            tfLotofacil.setText(nf.format(valorApostaLotofacil));
        }else if(cbLotofacil.getSelectedItem().equals("18")){
            qtdDezenasLotofacil = 18;
            valorApostaLotofacil = 1632.0;
            tfLotofacil.setText(nf.format(valorApostaLotofacil));
        }else if(cbLotofacil.getSelectedItem().equals("Escolha")){
            qtdDezenasLotofacil = 0;
            valorApostaLotofacil = 0.0;
            tfLotofacil.setText("");
        }
        
    }//GEN-LAST:event_cbLotofacilActionPerformed

    private void btLotofacilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLotofacilActionPerformed
        if(qtdDezenasLotofacil == 0){
            JOptionPane.showMessageDialog(null, "Selecione a Quantidade de Dezenas que Deseja Jogar.");
        }else{
            String dezena;
            sb = new StringBuilder();
            List<String> lotoFacil = new ArrayList<>();
            for(int i = 0; i < qtdDezenasLotofacil ; i++){
                dezena = GerarDezenas(1, 26);
                while(lotoFacil.contains(dezena)){
                    dezena = GerarDezenas(1, 26);
                }
                lotoFacil.add(dezena);
                
                sb.append("< ");
                sb.append(lotoFacil.get(i));
                sb.append(" >");
            }
            String SorteioLotofacil = sb.toString();
            taLotofacil.setText(SorteioLotofacil);
        }
    }//GEN-LAST:event_btLotofacilActionPerformed

    public static String GerarDezenas(int inicio, int fim){
        NumberFormat nfDezena = NumberFormat.getInstance();
        nfDezena.setMinimumIntegerDigits(2);
        int intervalo = fim - inicio;
        int numero = (int)(Math.random() * intervalo + inicio); 
        String dezena = nfDezena.format(numero);
        return dezena;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Metal (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Loterias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Loterias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Loterias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Loterias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Loterias().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btDuplasena;
    private javax.swing.JButton btLimparLotofacil;
    private javax.swing.JButton btLimparLotomania;
    private javax.swing.JButton btLimparMega;
    private javax.swing.JButton btLimparQuina;
    private javax.swing.JButton btLmparDuplasena;
    private javax.swing.JButton btLotofacil;
    private javax.swing.JButton btLotomania;
    private javax.swing.JButton btMegasena;
    private javax.swing.JButton btQuina;
    private javax.swing.JComboBox<String> cbDuplasena;
    private javax.swing.JComboBox<String> cbLotofacil;
    private javax.swing.JComboBox<String> cbMegasena;
    private javax.swing.JComboBox<String> cbQuina;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea taDuplasena;
    private javax.swing.JTextArea taLotofacil;
    private javax.swing.JTextArea taLotomania;
    private javax.swing.JTextArea taMegasena;
    private javax.swing.JTextArea taQuina;
    private javax.swing.JTextField tfDuplasena;
    private javax.swing.JTextField tfLotofacil;
    private javax.swing.JTextField tfMegasena;
    private javax.swing.JTextField tfQuina;
    // End of variables declaration//GEN-END:variables
}
